---
- name: restart apache
  service:
    name: "{{ apache_service }}"
    state: restarted
  environment:
    PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'


- name: reload apache
  service: name=httpd state=reloaded
  environment:
    PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

