---
# vars file for php

__php_webserver_daemon: "httpd"

__php_conf_path: /etc/php-7.0.conf
php_extension_conf_path: /etc/php-7.0.d

__php_apc_conf_filename: 50-apc.ini
__php_opcache_conf_filename: 10-opcache.ini
__php_fpm_daemon: php-fpm
__php_fpm_pool_conf_path: "/etc/php-fpm.d/www.conf"

php_enablerepo: "epel"

# Set this to false if you're not using PHP with Apache/Nginx/etc.
php_enable_webserver: false

# PHP-FPM configuration.
php_enable_php_fpm: false
php_fpm_listen: "127.0.0.1:9000"
php_fpm_pm_max_children: 45
php_fpm_pm_start_servers: 20
php_fpm_pm_min_spare_servers: 20
php_fpm_pm_max_spare_servers: 35
php_fpm_pm_max_requests:  500
# The executable to run when calling PHP from the command line.
php_executable: "php"

# OpCache settings (useful for PHP >=5.5).
php_opcache_enabled_in_ini: true

# APC settings (useful for PHP <5.5).
php_enable_apc: false
php_apc_enabled_in_ini: false
php_apc_cache_by_default: "1"
php_apc_shm_size: "96M"
php_apc_stat: "1"
php_apc_enable_cli: "0"

# If this is set to false, none of the following options will have any effect.
# Any and all changes to /etc/php.ini will be your responsibility.
php_use_managed_ini: true

php_expose_php: "On"
php_memory_limit: "128M"
php_max_execution_time: "30"
php_max_input_time: "60"
php_max_input_vars: "1000"
php_realpath_cache_size: "16K"
php_upload_max_filesize: "2M"
php_date_timezone: "Asia/Dubai"

php_sendmail_path: "/usr/sbin/sendmail -t -i"
php_short_open_tag: false

php_session_cookie_lifetime: 0
php_session_gc_probability: 1
php_session_gc_divisor: 1000
php_session_gc_maxlifetime: 1440
php_session_save_handler: files
php_session_save_path: ''

