---
# vars file for apache

apache_vhosts_ssl: []
apache_enablerepo: ""
apache_service: httpd
apache_daemon: httpd
apache_daemon_path: /usr/sbin/
apache_server_root: /etc/httpd
apache_conf_path: /etc/httpd/conf.d
apache_listen_port: 80
apache_listen_port_ssl: 443
apache_vhosts_version: "2.4"
apache_create_vhosts: true
apache_vhosts_filename: "vhosts.conf"

__apache_packages:
  - httpd24-tools-2.4.27
  - httpd24-2.4.27
  - gettext
  - yum-metadata-parser-python26-1.1.4
  - yum-python26-3.4.3

apache_packages:
  - httpd24-tools-2.4.27
  - httpd24-2.4.27
  - gettext
  - yum-metadata-parser-python26-1.1.4
  - yum-python26-3.4.3

apache_default_vhost_filename: 000-default.conf
apache_ports_configuration_items:
  - {
    regexp: "^Listen ",
    line: "Listen {{ apache_listen_port }}"
  }

apache_global_vhost_settings: ''

apache_ignore_missing_ssl_certificate: true

apache_ssl_protocol: "All -SSLv2 -SSLv3"
apache_ssl_cipher_suite: "AES256+EECDH:AES256+EDH"


# Set initial apache state. Recommended values: `started` or `stopped`
apache_state: started
